---
- name: Copy files from the local machine to a remote machine
  hosts: prod
  vars_files:
    - common_vars.yml
  tasks:
    - name: 刪除遠端目標目錄（如果存在）
      file:
        path: "{{ target_path }}"
        state: absent
    - name: Copy files to remote devBuild folder
      copy:
        src: "{{ src_build_path }}"
        dest: "{{ target_path }}"
        owner: oomii # 设置目标文件夹的所有者
        group: oomii # 设置目标文件夹的所属组
        mode: "0755" # 设置目标文件夹的权限，根据需要进行调整

